import React from 'react'
import './Biocharcontainer.scss'


const BiocharContainer = () => {
  return (
    <div className='biochar_container'>
<div className='biochar_div1'>
  <div className='parent'>
  <div className='bio_subdiv1'>
   <h1 className='bio_heading'><span>Organic Green Carbon</span><p> (Biochar)</p><br/><img src="\leafimage.png" alt="image" /></h1>
   <p className='bio_para'>1.ORGANIC GREEN CARBON IS A CARBON-RICH PRODUCT MADE FROM RENEWABLE AGRICULTURAL/WOODY BIOMASS WASTE RESIDUE. WE PRODUCE IT THROUGH GASIFICATION OF BAMBOO WASTE (HEATING IN THE ABSENCE OF OXYGEN) .IT CAN BE USED EITHER ALONE OR MIXED WITH ORGANIC ADDITIVES IN SUITABLE RATIO .IT ACTS AS A SUSTAINABLE AND PERMANENT SOIL AMENDMENT AGENT AND ALSO AS GROWING MEDIA FOR PLANTS. ORGANIC GREEN CARBON HAS TREMENDOUS POTENTIAL FOR WATER CONSERVATION IN AGRICULTURE AND HORTICULTURE ,SPECIALLY IN POLY HOUSES/GREEN HOUSES AND NEW PLANTATIONS . IT IS VERY USEFUL IN AREAS WHERE WATER IS SCARCE AND SOIL IS DEGRADED.IT IS A SOIL AMENDMENT THAT IS PLOWED-IN ONLY ONCE AND HAS A LASTING EFFECT FOR CENTURIES. ORGANIC GREEN CARBON ENHANCES SOIL FERTILITY BY STIMULATING BIOLOGICAL ACTIVITY, IMPROVING SOIL NUTRIENT AND WATER RETENTION, AND ALSO INCREASING SOIL ORGANIC MATTER.IT IS COMPLETELY SUSTAINABLE AS IT COMES FROM READILY AVAILABLE AND SUSTAINABLE BIOMASS WASTE. FURTHERMORE, THE CARBON IN THE ORGANIC GREEN CARBON BECOMES LOCKED UP IN THE SOIL, REMOVING CARBON FROM THE ATMOSPHERE AND FACILITATES CLIMATE CHANGE MITIGATION.
THE MAIN SCIENTIFICALLY APPROVED REASONS THAT ORGANIC CARBON AMENDMENTS HAVE RESULTED IN MEASURABLE IMPROVEMENTS IN SOIL PRODUCTIVITY ARE THAT IT: • REPAIRS DEGRADED SOILS ,RESISTS SOIL EROSION
• INCREASES YIELD BY 5 - 40%
• ENHANCES SOIL BIOLOGY (40% INCREASE IN MYCORRHIZAL FUNGI)
• IMPROVES NUTRIENT RETENTION IN SOILS (50% INCREASE IN CATION EXCHANGE CAPACITY)
• IMPROVES THE WATER RETENTION CAPACITY OF SOILS (UP TO 20 % INCREASE),THUS EFFECTIVELY REDUCES WATER REQUIRED FOR IRRIGATING THE SOIL FOR
CROP PRODUCTION • INCREASES SOIL ORGANIC MATTER
• FACILITATES REDUCTION OF NEED FOR CHEMICAL FERTILIZER ,THUS FURTHER REDUCING WATER REQUIRED FOR IRRIGATION
• IMPROVES SOIL DRAINAGE,FACILITATES MORE NEUTRAL PH
• REDUCED SOIL COMPACTION ,INCREASED NUTRIENT CYCLING
• GREATER RETENTION OF WATER IN DRY SOILS
• IMPROVES GERMINATION
• IMPROVES PLANT RESISTANCE TO FUNGAL DISEASE, ROOT FEEDING NEMATODES AND INSECT INFESTATIONS
ANOTHER VERY IMPORTANT APPLICATION OF BIOCHAR IS AS AN AGENT FOR CLIMATE CHANGE MITIGATION.LARGE AMOUNTS OF FORESTRY AND AGRICULTURAL RESIDUES AND OTHER BIOMASS ARE CURRENTLY BURNED OR LEFT TO DECOMPOSE THEREBY RELEASING CARBON DIOXIDE (CO2) AND/OR METHANE (CH4)—TWO MAIN GREENHOUSE GASES (GHGS)—INTO THE ATMOSPHERE. UNDER BIOCHAR CONVERSION SCENARIOS, EASILY MINERALIZED CARBON COMPOUNDS IN BIOMASS ARE CONVERTED INTO FUSED CARBON RING STRUCTURES IN BIOCHAR AND PLACED IN SOILS WHERE THEY PERSIST FOR HUNDREDS OR THOUSANDS OF YEARS. WHEN DEPLOYED ON A GLOBAL SCALE THROUGH THE CONVERSION OF GIGATONNES OF BIOMASS INTO BIOCHAR, STUDIES HAVE SHOWN THAT BIOCHAR HAS THE POTENTIAL TO MITIGATE GLOBAL CLIMATE CHANGE BY DRAWING DOWN ATMOSPHERIC GHG CONCENTRATIONS . BIO CHAR ALSO IDENTIFIES AS CLIMATE CHANGE MITIGATION AGENT BY IPCC (INTERGOVERNMENTAL PANEL ON CLIMATE CHANGE). //EFFECT OF BIOCHAR ON DIFFERENT SOIL PROPERTIES</p>

</div>

<div className='bio_subdiv2'>
<img className='bio_container_img bio_container_img1 ' src="\biochar4.jpg"  alt="image" /><br/>
<img className='bio_container_img bio_container_img2' src="\biocharimg3.jpg"  alt="image" />

</div>

  </div>
  <button className='btnbtn newbtn'>Read More</button>
    

</div>
<div className='biochar_div1'>
  <div className='parent'>
  <div className='bio_subdiv1'>
  <h2 className='bio_heading'><span>Activated Bamboo</span> (Charcoal)<br/><img src="\leafimage.png" alt="image" /></h2>
   <p className='bio_para'>IT IS BASICALLY USED AS AN ABSORBANT AND DEODORIZER
• PHARMACEUTICALS & BULK DRUG INDUSTRIES.
• FERTILIZER UNITS & PETROLEUM REFINERIES AS A CATALYST CARRIER.
• PURIFICATION & DE-COLORIZATION OF PLASTICIZERS, GLYCERIN, PARAFFIN,WAXES, FINE
• CHEMICALS, DYES & INTERMEDIATES, ORGANIC ACID, GLUCOSE AND LACTOSE SOLUTIONS,
• DEODORIZATION OF GELATIN AND LIQUEFIED PETROLEUM JELLY.
• BLEACHING DEODORIZING OF VEGETABLE OIL, EDIBLE OIL & FATS.
• SUGAR INDUSTRIES & THERMAL AND NUCLEAR POWER STATION.
• BREWERIES AND WINE MAKING INDUSTRIES.
• POLLUTION CONTROL EQUIPMENT & ELECTRO PLATING CHEMICALS.
• FACE MASKS FOR AIR POLLUTION MITIGATION
• USE IN BEAUTY PRODUCTS
• USE IN FOOD PRODUCTS
• USE FOR INCREASING SHELF LIFE OF FRUITS AND VEGETABLES
• FOR REMOVING UNDESIRABLE COMPONENTS & COLOR CORRECTION IN ALL TYPES OF INDUSTRIES.
</p>
</div>

<div className='bio_subdiv2'>
<img className='bio_container_img' src="\biocharimg2.jpg" alt="" />

</div>

  </div>
  <button className='btnbtn newbtn'>Read More</button>
    

</div>


<div className='biochar_div1'>
  <div className='parent'>
  <div className='bio_subdiv1'>
  
<h1 className='bio_heading'><p id='product'>PRODUCT</p><span>Bamboo Charcoal</span> (Briquette)<br/><img src="\leafimage.png" alt="image" /></h1>
<p className='bio_para'>USED IN BIOMASS GASSIFIERS AS FUEL FOR THERMAL USE OR FOR ELECTRICITY PRODUCTION, BAMBOO CHARCOAL HAS A VERY HIGH CALORIFIC VALUE AND LOW ASH CONTENT AS COMPARED TO WOOD COAL.</p>

</div>

<div className='bio_subdiv2'>
<img className='bio_container_img bio_container_img3' src="\biocharproduct.jpg" alt="" />

</div>

</div>
  <button className='btnbtn newbtn'>Read More</button>
    

</div>
  



        </div>
  )
}

export default BiocharContainer